### ISSUE TITLE
100V chip capacitors

### ISSUE THREAD

**Issue by g4ixt** [bg3mdo/budget_23cm_band_RF_power_amplifier#2]
It is hard to find 100V 0603 NP0/C0G capacitors in small quantities, for C17, C18, C8, C9.  I can get 50V ones, or in 0805 package can get 100V ones.  Would the larger size of 0805 be a problem at that part of the circuit?

Could you provide some details of how you fixed the transistors?  I am thinking of using low temperature 137C Sn/Bi solder paste and a temperature controlled hotplate to solder them onto a copper plate the size of the two half boards and transistor, bolted to a larger heatsink.

I would also be interested to know the dimensions of heatsink you used.  I bought two transistors so will build two amplifiers in the hope that one of them will work.  If both work I might build a combiner, but at the moment I can only generate 1W of drive power so I will also need a driver amplifier.

**Comment by dh2wq** [comment]
@g4ixt 50V types should be fine at the input. You may have look on DF9IC presentation regarding soldering. He uses Sn42Bi58 Paste. (http://www.df9ic.de/doc/2015/mmrt_2015/mmrt_2015_1296MHz_PAs.pdf)

@bg3mdo can you please provide the Altium Sources? I haven‘t built a pa on this power at 23cm or above and I would like to test some modifications to gain more experience.
